netcoreapp20
aspnet/WebSockets pull request #173
Opened 2017-05-04 21:18 UTC by anurse

```
Microsoft.AspNetCore.WebSockets.2.0.0-preview1-t004670c39 -> netcoreapp2.0
```

2017-05-04 21:42 UTC, mikeharder requested changes
Change base branch to preview1

2017-05-04 21:50 UTC, anurse commented
Done

2017-05-04 21:53 UTC, mikeharder approved these changes

2017-05-04 22:06 UTC, muratg approved these changes

2017-05-05 02:26 UTC, merged

2017-05-05 04:28 UTC, Eilon commented on test/Microsoft.AspNetCore.WebSockets.Test/Microsoft.AspNetCore.WebSockets.Test.csproj
>      <PlatformTarget Condition="'$(TargetFramework)' == 'net46'">x64</PlatformTarget>
Remove this condition?